### ISSUE TITLE
Apache Version Information Disclosure

### ISSUE THREAD

**Issue by l4rm4nd** [DRK-Odenwaldkreis/Testerfassung#10]
**Issue**
The Apache web server of your public website leaks detailed version information in HTTP response headers.

**Proof**
![image](https://user-images.githubusercontent.com/21357789/158897239-b9412e1a-b5a8-4554-8b6b-9bc4be59667f.png)

**Recommendation**
https://www.tecmint.com/hide-apache-web-server-version-information/

**Comment by mbay-ODW** [comment]
Thanks for checking, we will change that together with the other issues you raised.

**Comment by mbay-ODW** [comment]
Done!

**Comment by l4rm4nd** [comment]
confirmed!
