### ISSUE TITLE
Apache Directory Listing enabled

### ISSUE THREAD

**Issue by l4rm4nd** [DRK-Odenwaldkreis/Testerfassung#9]
**Issue**
The Apache web server of your public website allows for directory indexing and may disclose sensitive files.

**Proof**
https://testzentrum-odw.de/download/

![image](https://user-images.githubusercontent.com/21357789/158895338-e3668597-aea2-49fd-9add-50a5b5c8afe0.png)

**Recommendation**
https://www.simplified.guide/apache/disable-directory-listing

**Comment by mbay-ODW** [comment]
Thanks for your input, we will change that with the other issues you raised.

**Comment by mbay-ODW** [comment]
Done!

**Comment by l4rm4nd** [comment]
confirmed!
